#!/bin/sh
set -e

SITE=$1
SRC_DIR="/sources/$SITE"
OUT_DIR="/sites/$SITE"

if [ ! -d "$SRC_DIR" ]; then
	mkdir -p "$SRC_DIR"

	if [ $PRIVATE = "true" ]; then
		CLONE_URL=$CLONE_URL_SSH
	else
		CLONE_URL=$CLONE_URL_HTTPS
	fi

	git clone --recursive "$CLONE_URL" "$SRC_DIR"
fi

cd $SRC_DIR
git fetch
echo "Checking out $COMMIT"
git checkout --quiet $COMMIT

if [ -r ".gitmodules" ]; then
	git submodule sync --recursive
	git submodule update --init --recursive
fi

echo "Building $SITE to $OUT_DIR"
hugo -v -d "$OUT_DIR"
